// Job
export const SAVE_JOB_LIST = 'SAVE_JOB_LIST'
export const SAVE_JOB_LOADING = 'SAVE_JOB_LOADING'

// Cluster
export const SAVE_CLUSTER_INFO = 'SAVE_CLUSTER_INFO'
export const SAVE_CLUSTER_DETAIL_LOADING = 'SAVE_CLUSTER_DETAIL_LOADING'
export const UPDATE_CLUSTER_INSTANCES = 'UPDATE_CLUSTER_INSTANCES'

// AppId
